### PR TITLE
Created Hilgendorf MoveIt! Test Package

### PR DESCRIPTION
**Pull request by davetcoleman**
Full demonstration of C++ control of dual arm robot using MoveIt! - no GUI. Currently I have been testing a re-vamped version of my experience planner, which I am tentatively calling Bolt. This package has lots of hooks into OMPL such that I can generate discretized roadmaps of the robot in joint space. It allows me to easily save those roadmaps to file.

More high level - this simple script generates two random configurations and plans between them using MoveIt! and OMPL components. My intention is to have it handle dual arms, but currently it is only planning for one arm.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@Jmeyer1292, can you please review.  I'd like to get this PR reviewed by COB 3/1.

**Comment by Jmeyer1292** [comment]
@davetcoleman Forgive the possibly dumb question, but where does one find the `moveit_ompl` package?

**Comment by Jmeyer1292** [comment]
Furthermore, is this meant to be used under Jade, Indigo, or either?

**Comment by davetcoleman** [comment]
I had the repo private, it is now here: https://github.com/davetcoleman/moveit_ompl

It should work with either, though I'm currently on Indigo because some Hilgendorf dependencies are missing from Jade

**Comment by Jmeyer1292** [comment]
@davetcoleman Thank you. Forgive the break between now and our last comments, got a bit busy last week. 

Now I'm to the point where it appears that I'll need to build the newest version of OMPL. Do I need the latest moveit too? For OMPL, which is not a 'catkin' package, do you have a specific strategy for managing different versions? 

I built a separate version of OMPL's main branch, but it does not appear to contain your Bolt planner header files. Could you point me to the correct location?

**Comment by davetcoleman** [comment]
Actually, currently you will probably need to build from source a lot of packages:

hrl_kinematics/
moveit_boilerplate/
moveit_core/
moveit_hrp2/
moveit_humanoid/
moveit_msgs/
moveit_ompl/
moveit_plugins/
moveit_ros/
moveit_sim_controller/
moveit_visual_tools/
ompl_experience_demos/
ompl_visual_tools/
ros_control/
ros_control_boilerplate/
ros_controllers/
rviz_visual_tools/
srdfdom/
curie/
hilgendorf/
robotiq/
universal_robot/

I'm not sure at this point which commit you'll need

**Comment by Jmeyer1292** [comment]
@davetcoleman  Thank you for enumerating these. ROS packages are no problem, as they are easily version managed. What about OMPL? What are the requirements, and what branch contains your implementation of Bolt? Headers in moveit_ompl require this.

**Comment by davetcoleman** [comment]
I need to spend some time documenting all the versions and repos, I just haven't yet

**Comment by shaun-edwards** [comment]
The install procedure needs to be documented so that we can test and verify changes here at SwRI.  Please spend the time to do this as we have gone several weeks without a PR.

Is it easier to switch to Jade for the packages listed above and then download the ROS-I packages from source?

**Comment by shaun-edwards** [comment]
ping.

**Comment by davetcoleman** [comment]
My repos have progressed pretty far since this PR and none of the HEADs will compile correctly anymore. Not sure what commit IDs this would require to work. I didn't realize you guys would want to compile everything - that's just really tough given the number of things it touches.

**Comment by davetcoleman** [comment]
Shaun I'll send you an email update now

**Pull request closed without merging**
